/**
 * Account Management services — business rules and data access.
 *
 * Epic: FR-ACC  ·  Owner: Afham
 *
 * This is where the acceptance criteria in docs/requirements.md are actually
 * enforced. Import the shared Prisma client from ../../lib/prisma — never
 * construct your own.
 */
import prisma from "../../lib/prisma.js";
import AppError from "../../utils/AppError.js";
import { encryptNic, getNicLast4 } from "./nicCrypto.js";
import { hashPassword, verifyPassword } from "./passwordHash.js";
import { verifyFirebaseIdToken } from "./firebaseAuth.js";
import { signToken } from "../../lib/jwt.js";
import { isSuspended } from "../../lib/accountStatus.js";
import crypto from "crypto";
import { generateOtp, verifyOtp } from "./otpService.js";
import config from "../../config/index.js";
import { isBlocked, record, clear } from "./attemptLimiter.js";

const MIN_AGE = 18;
const VALID_ROLES = ["YOUTH_JOB_SEEKER", "EMPLOYER", "COMMUNITY_ENDORSER"];

// Registration never needs this — the phone comes straight from a
// Firebase-verified ID token, always clean E.164. Password login is the
// one place a phone number is hand-typed (or pasted from Contacts) into a
// text field, so "+94 77 123 4567" needs to match the "+94771234567"
// stored from registration. Strips whitespace/dashes/parens only — not a
// full phone-parsing library, since the actual failure this fixes is
// formatting noise around an otherwise-correct number, not arbitrary
// input correction.
function normalizePhoneForLookup(phone) {
  return phone.replace(/[\s\-()]/g, "");
}

// Emails are matched and stored case-insensitively: "A@x.com" and "a@x.com" are one
// mailbox, and the email is a recovery channel (FR-ACC-10), so two spellings must not
// become two accounts or let someone slip past the duplicate check.
function normalizeEmail(email) {
  return email.trim().toLowerCase();
}

// Tokens e-mailed to people are stored only as a SHA-256 hash, so a database leak does
// not hand out working reset links. The raw token exists only in the e-mail.
function hashToken(token) {
  return crypto.createHash("sha256").update(String(token)).digest("hex");
}

// The device id on a recovery request is the only secret binding an approved recovery to
// the phone that asked (schema: AccountRecoveryRequest.deviceId). It is generated by the
// app with a secure random source; reject anything that cannot be one so a guessable or
// shared value ("dummy-device-id") never becomes a bearer credential.
const DEVICE_ID_FORMAT = /^[A-Za-z0-9_-]{32,128}$/;
function assertDeviceId(deviceId) {
  if (typeof deviceId !== "string" || !DEVICE_ID_FORMAT.test(deviceId)) {
    throw AppError.badRequest("deviceId must be a 32-128 character random identifier.");
  }
}

// What the person is told when the app cannot deliver a code or link (there is no SMS or
// email provider in this project yet). In development the code/link is printed to the
// server console so the flow can be exercised end to end; production prints nothing.
function deliverInDevelopment(kind, destination, secret) {
  if (config.env !== "production") {
    console.log(`[Mock ${kind}] for ${destination}: ${secret}`);
  }
}

// Reset requests per phone (each sends an SMS) and wrong reset codes per phone.
const RESET_REQUEST_LIMIT = { max: 3, windowMs: 15 * 60 * 1000 };
const RESET_CODE_FAILURE_LIMIT = { max: 5, windowMs: 15 * 60 * 1000 };
const PHONE_CHANGE_FAILURE_LIMIT = { max: 5, windowMs: 15 * 60 * 1000 };
const RESET_TOKEN_MINUTES = 15;
const EMAIL_CONFIRM_HOURS = 24;

// FR-ACC-09 / NFR-SEC-02: 5 consecutive failed password attempts locks the
// password path for 15 minutes. Only the password path — FR-ACC-07 deliberately
// keeps OTP login independent so it stays available when password login doesn't.
const LOCKOUT_THRESHOLD = 5;
const LOCKOUT_DURATION_MS = 15 * 60 * 1000;
const LOCKED_MESSAGE =
  "Too many attempts — password login is paused for 15 minutes. You can log in with a code instead.";
const CLEARED_LOCKOUT = { failedLoginAttempts: 0, lockedUntil: null };

// Prototype 1.6sus / 1.7sus: each path names the OTHER path, since neither will work.
const SUSPENDED_ON_PASSWORD_PATH =
  "This account has been suspended. Staff make that decision and it takes effect immediately. Logging in with a code will not work either, and YouthLink has no appeals process.";
const SUSPENDED_ON_OTP_PATH =
  "This account has been suspended. Staff make that decision and it takes effect immediately. Trying the password instead will not work either, and YouthLink has no appeals process.";

// Not a real account's hash — a fixed bcrypt hash of an arbitrary string,
// compared against on an unregistered-phone login attempt so the response
// takes roughly the same time as a real wrong-password attempt (which runs
// a real bcrypt.compare). Without this, response latency alone would let a
// caller enumerate registered phone numbers even though the error message
// is identical either way — caught in self-review.
const DUMMY_PASSWORD_HASH =
  "$2b$12$M5aYuTGsgzTQZq0ATSNOBuhbJmRM7dgpCEhSo/Byd2XJedYLlRX3S";

// Shared by loginWithOtp and (indirectly, see its own inline version)
// loginWithPassword's success case. Runs inside its own row-locked
// transaction rather than a plain conditional update — a conditional
// update only guarantees ITS OWN write is atomic; it says nothing about
// whether the "should I clear this?" decision is still accurate by the
// time the write actually runs. Without the lock, this call could land
// between a *different*, concurrent request's own read and write — e.g.
// that request's 5th failed attempt, mid-flight, about to set a fresh
// lockout — and this call would see "something's set, clear it" and wipe
// out a lock that request was still in the middle of applying. Confirmed
// live before this fix existed: a successful login and a concurrent
// locking failure could land in the same instant, and the lock vanished.
// `FOR UPDATE` forces any other request touching this same row to wait
// until this transaction finishes, so nothing can change the row between
// the read and the write here.
async function clearLockout(userId) {
  await prisma.$transaction(async (tx) => {
    const [row] = await tx.$queryRaw`
      SELECT "failedLoginAttempts", "lockedUntil"
      FROM "User"
      WHERE "id" = ${userId}
      FOR UPDATE
    `;
    if (row.failedLoginAttempts !== 0 || row.lockedUntil) {
      await tx.user.update({ where: { id: userId }, data: CLEARED_LOCKOUT });
    }
  });
}

function calculateAge(birthdate) {
  const today = new Date();
  let age = today.getUTCFullYear() - birthdate.getUTCFullYear();
  const monthDiff = today.getUTCMonth() - birthdate.getUTCMonth();
  if (
    monthDiff < 0 ||
    (monthDiff === 0 && today.getUTCDate() < birthdate.getUTCDate())
  ) {
    age--;
  }
  return age;
}

/**
 * Required-field and shape checks. Deliberately separate from the
 * requirement checks below (age gate, ToS, phone verification, duplicate
 * prevention) — this is "was the request well-formed at all", not
 * business rules.
 */
const EMAIL_FORMAT = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

function validateFields({
  role,
  idToken,
  password,
  email,
  nic,
  birthdate,
  legalName,
  tosAccepted,
}) {
  const fields = {};

  if (!VALID_ROLES.includes(role)) {
    fields.role = `Must be one of: ${VALID_ROLES.join(", ")}`;
  }
  if (!idToken || typeof idToken !== "string") {
    fields.idToken = "Required";
  }
  if (!password || typeof password !== "string") {
    fields.password = "Required";
  } else if (password.length < 8 || password.length > 64) {
    fields.password = "Must be between 8 and 64 characters";
  }
  // email is optional (User.email is nullable) — only checked if provided.
  // Trimmed first: mobile keyboards routinely append a space, and the address is stored
  // trimmed and lower-cased anyway (see normalizeEmail).
  if (email && (typeof email !== "string" || !EMAIL_FORMAT.test(email.trim()))) {
    fields.email = "Must be a valid email address";
  }
  const NIC_FORMAT = /^(\d{12}|\d{9}[vVxX])$/;
  if (!nic || typeof nic !== "string" || !NIC_FORMAT.test(nic.trim())) {
    fields.nic = "Must be 12 digits, or 9 digits followed by V or X";
  }
  if (!birthdate || Number.isNaN(new Date(birthdate).getTime())) {
    fields.birthdate = "Required, must be a valid date";
  }
  if (
    !legalName ||
    typeof legalName !== "string" ||
    legalName.trim().length === 0
  ) {
    fields.legalName = "Required";
  } else if (legalName.trim().length > 100) {
    fields.legalName = "Must be 100 characters or fewer";
  }
  if (typeof tosAccepted !== "boolean") {
    fields.tosAccepted = "Required";
  }

  if (Object.keys(fields).length > 0) {
    throw AppError.badRequest(
      "Registration form is incomplete or invalid.",
      fields,
    );
  }
}

/**
 * FR-ACC-05: pre-check for a friendly, field-level error before OTP is sent.
 * @param {object} input
 * @param {string} [input.phone]
 * @param {string} [input.email]
 * @returns {Promise<{ phoneTaken: boolean, emailTaken: boolean }>}
 */
async function checkAvailability({ phone, email }) {
  const result = { phoneTaken: false, emailTaken: false };

  if (phone) {
    const normalizedPhone = normalizePhoneForLookup(phone);
    const existingPhone = await prisma.user.findFirst({
      where: {
        phone: normalizedPhone,
        phoneVerifiedAt: { not: null },
        deletedAt: null,
      },
      select: { id: true },
    });
    if (existingPhone) {
      result.phoneTaken = true;
    }
  }

  if (email) {
    const existingEmail = await prisma.user.findFirst({
      where: { email: { equals: normalizeEmail(email), mode: "insensitive" }, deletedAt: null },
      select: { id: true },
    });
    if (existingEmail) {
      result.emailTaken = true;
    }
  }

  return result;
}

/**
 * FR-ACC-01. Registration is a single atomic submission — see
 * docs/decisions.md for why. The client completes Firebase phone
 * verification first; this function takes the resulting ID token
 * alongside every other field and either creates one complete, ACTIVE
 * account or fails entirely. No partial/pending row is ever created.
 *
 * @param {object} input
 * @param {"YOUTH_JOB_SEEKER"|"EMPLOYER"|"COMMUNITY_ENDORSER"} input.role
 * @param {string} input.idToken - Firebase ID token from client-side phone verification.
 * @param {string} input.password
 * @param {string} [input.email]
 * @param {string} input.nic
 * @param {string} input.birthdate - ISO date string.
 * @param {string} input.legalName
 * @param {boolean} input.tosAccepted
 * @returns {Promise<object>} The created User row.
 */
async function register(input) {
  validateFields(input);
  const {
    role,
    idToken,
    password,
    email,
    nic,
    birthdate,
    legalName,
    tosAccepted,
  } = input;

  // Cheap, no-I/O checks first — fail fast before spending a Firebase call
  // or a DB round trip on a request that was never going to succeed.

  if (!tosAccepted) {
    throw AppError.badRequest(
      "You must accept the Terms of Service and Privacy Policy.",
      {
        tosAccepted: "Required",
      },
    );
  }

  const birthdateValue = new Date(birthdate);

  // FR-ACC-03/FR-ACC-04: age gate reads only the self-declared birthdate,
  // never the NIC — no exceptions, no override path.
  if (calculateAge(birthdateValue) < MIN_AGE) {
    throw AppError.badRequest("You must be 18 or older to register.", {
      birthdate: "Must indicate an age of 18 or older",
    });
  }

  // FR-ACC-01 AC1 / FR-ACC-08: the phone is only treated as verified once
  // the Firebase ID token itself is validated server-side.
  let phoneNumber;
  try {
    ({ phoneNumber } = await verifyFirebaseIdToken(idToken));
  } catch (err) {
    // Log the real cause server-side — this catch also covers Firebase
    // Admin misconfiguration or an outage, not just a bad/expired token,
    // and those need to be diagnosable even though the client only ever
    // sees one generic message either way.
    console.error("verifyFirebaseIdToken failed during registration:", err);
    throw AppError.unauthorized(
      "Phone verification failed or has expired. Verify your phone again.",
    );
  }

  const nicEncrypted = encryptNic(nic);

  // FR-ACC-05: pre-check for a friendly, field-level error. The partial
  // unique indexes on User.phone/User.nicEncrypted (see
  // docs/database-schema.md) are the actual enforcement and still apply
  // as a safety net in the create() below, in case of a race between
  // this check and the insert.
  const [existingPhone, existingNic, existingEmail] = await Promise.all([
    prisma.user.findFirst({
      where: {
        phone: phoneNumber,
        phoneVerifiedAt: { not: null },
        deletedAt: null,
      },
      select: { id: true },
    }),
    prisma.user.findFirst({
      where: { nicEncrypted, deletedAt: null },
      select: { id: true },
    }),
    email ? prisma.user.findFirst({
      where: { email: { equals: normalizeEmail(email), mode: "insensitive" }, deletedAt: null },
      select: { id: true },
    }) : Promise.resolve(null),
  ]);

  if (existingPhone) {
    throw AppError.conflict("That phone number is already registered.", {
      phone: "Already registered",
    });
  }
  if (existingNic) {
    throw AppError.conflict("That NIC is already registered.", {
      nic: "Already registered",
    });
  }
  if (existingEmail) {
    throw AppError.conflict("That email address is already in use.", {
      email: "Already in use",
    });
  }

  const passwordHashValue = await hashPassword(password);
  const nicLast4 = getNicLast4(nic);

  let user;
  try {
    user = await prisma.user.create({
      data: {
        role,
        phone: phoneNumber,
        phoneVerifiedAt: new Date(),
        passwordHash: passwordHashValue,
        email: email ? normalizeEmail(email) : null,
        nicEncrypted,
        nicLast4,
        legalName: legalName.trim(),
        birthdate: birthdateValue,
        tosAcceptedAt: new Date(),
        accountStatus: "ACTIVE",
      },
    });
  } catch (err) {
    // Safety net for a race between the pre-check above and this insert —
    // the partial unique indexes are the real enforcement either way.
    if (err.code === "P2002") {
      throw AppError.conflict(
        "That phone number or NIC is already registered.",
      );
    }
    throw err;
  }

  // FR-ACC-01 AC4: an email given at signup is confirmed once through a link; until then
  // it stays unverified and registration is not blocked by it. A failure to create the
  // link must not undo an account that already exists.
  if (user.email) {
    try {
      await sendEmailConfirmation(user);
    } catch (err) {
      console.error("Could not create the email confirmation link:", err);
    }
  }
  return user;
}

/** Creates a single-use confirmation link for the account's current email address. */
async function sendEmailConfirmation(user) {
  const token = crypto.randomBytes(32).toString("hex");
  await prisma.emailVerificationToken.create({
    data: {
      userId: user.id,
      email: user.email,
      token: hashToken(token),
      purpose: "SIGNUP",
      expiresAt: new Date(Date.now() + EMAIL_CONFIRM_HOURS * 60 * 60 * 1000),
    },
  });
  deliverInDevelopment(
    "Email",
    user.email,
    `${config.publicBaseUrl}/api/account/verify-email?token=${token}`,
  );
}

/**
 * FR-ACC-01 AC4 / FR-ACC-05: the person opened the confirmation link, so the email is
 * now verified. The token is consumed in the same statement that checks it, so a link
 * cannot be used twice.
 * @param {{ token: string }} input
 * @returns {Promise<{ status: "confirmed"|"invalid"|"taken" }>}
 */
async function verifyEmail({ token }) {
  if (!token || typeof token !== "string") return { status: "invalid" };
  const tokenHash = hashToken(token);

  const row = await prisma.emailVerificationToken.findFirst({
    where: { token: tokenHash, purpose: "SIGNUP", consumedAt: null, expiresAt: { gt: new Date() } },
    include: { user: true },
  });
  // The link only counts while the account still holds the address it was sent to.
  if (!row || !row.user || row.user.deletedAt || row.user.email !== row.email) {
    return { status: "invalid" };
  }

  try {
    await prisma.$transaction(async (tx) => {
      const claimed = await tx.emailVerificationToken.updateMany({
        where: { id: row.id, consumedAt: null },
        data: { consumedAt: new Date() },
      });
      if (claimed.count === 0) throw new AppError(409, "used");
      await tx.user.update({ where: { id: row.userId }, data: { emailVerifiedAt: new Date() } });
    });
  } catch (err) {
    // 409 "used": another request spent the link first. P2002: someone else confirmed the
    // same address meanwhile — verified emails are unique (FR-ACC-05).
    if (err.code === "P2002") return { status: "taken" };
    if (err instanceof AppError) return { status: "invalid" };
    throw err;
  }
  return { status: "confirmed" };
}

/**
 * FR-ACC-07 password login path. Kept deliberately independent of the OTP
 * path below — a working password must log a user in even if SMS delivery
 * is failing (FR-ACC-07 AC2).
 *
 * @param {object} input
 * @param {string} input.phone
 * @param {string} input.password
 * @returns {Promise<{ token: string, user: object }>}
 */
async function loginWithPassword({ phone, password }) {
  if (!phone || typeof phone !== "string") {
    throw AppError.badRequest("Phone is required.", { phone: "Required" });
  }
  if (!password || typeof password !== "string") {
    throw AppError.badRequest("Password is required.", {
      password: "Required",
    });
  }

  const user = await prisma.user.findFirst({
    where: { phone: normalizePhoneForLookup(phone), deletedAt: null },
  });

  // Same generic message whether the phone isn't registered or the password
  // is wrong — telling the two apart would let a caller enumerate registered
  // phone numbers.
  // The two strings the prototype draws (1.6bnr1, 1.6bnr2). The remaining-attempts
  // warning appears only once two or fewer are left (FR-ACC-09 E6), not on every miss.
  const invalidCredentials = (remaining) => {
    if (remaining !== undefined && remaining > 0 && remaining <= 2) {
      return AppError.unauthorized(
        `We couldn't log you in with those details. ${remaining} attempt${remaining === 1 ? "" : "s"} left before password login is paused for 15 minutes.`,
      );
    }
    return AppError.unauthorized(
      "We couldn't log you in with those details. Check your number and password, or reset your password.",
    );
  };

  if (!user) {
    // Burn roughly the same time a real password check would take, so an
    // unregistered phone isn't distinguishable from a wrong password by
    // response latency alone.
    await verifyPassword(password, DUMMY_PASSWORD_HASH);
    throw invalidCredentials();
  }

  // Verified before any lockout decision, deliberately, even though the
  // result is discarded when locked — this is what makes a locked account
  // take the same time to reject as every other case. Checking the lock
  // first and skipping this call for a locked account made a locked
  // account answer faster than any other rejection, since it alone never
  // paid bcrypt's cost — a real, exploitable timing side-channel: an
  // attacker who already suspects a phone number is registered can lock it
  // with 5 wrong passwords, then time a 6th request; a fast response
  // confirms the account exists and is locked, something an unregistered
  // phone could never produce, despite an identical error message either
  // way. The same trade-off DUMMY_PASSWORD_HASH already makes for an
  // unregistered phone above — pay bcrypt's cost to keep two different
  // rejection reasons looking identical from the outside — applied here to
  // a locked account instead of a nonexistent one. Run here, outside the row lock below, on purpose — bcrypt is slow
  // by design, and holding a row lock across it would serialize every
  // concurrent login attempt against the same account behind that delay,
  // including the multiple-simultaneous-logins case this product
  // explicitly supports.
  const passwordCorrect = await verifyPassword(password, user.passwordHash);

  // Every read and write of failedLoginAttempts/lockedUntil for this
  // attempt happens inside one transaction that holds a row lock
  // (`SELECT ... FOR UPDATE`) on this user for its whole duration. Two
  // earlier fixes here — an atomic increment, a conditional updateMany —
  // each made their own single write safe, but neither closed this: a
  // *decision* made from a value read outside any lock (e.g. "is this
  // account currently locked?") could still go stale if a different,
  // concurrent request changed the row in between the read and the write.
  // Confirmed live before this fix existed: a successful login here could
  // land in the same instant as a concurrent request's 5th failed attempt,
  // and this function's own success-path clear would wipe out the lock the
  // other request had just set — a free bypass of a 15-minute lockout. The
  // row lock forces concurrent requests against this same account to run
  // one at a time for this whole decide-and-write step, closing the gap
  // structurally rather than reasoning about every possible interleaving
  // by hand. `FOR UPDATE` has no equivalent in Prisma's query API, which is
  // why this one step drops to raw SQL — the same reasoning as the
  // partial unique indexes in the initial migration: Prisma's abstraction
  // genuinely can't express this, so raw SQL is the correct, minimal
  // escape hatch, not a stylistic choice.
  const outcome = await prisma.$transaction(async (tx) => {
    const [row] = await tx.$queryRaw`
      SELECT "failedLoginAttempts", "lockedUntil"
      FROM "User"
      WHERE "id" = ${user.id}
      FOR UPDATE
    `;

    const now = new Date();
    // A lockout window that has already elapsed is treated as cleared
    // before evaluating this attempt, giving a fresh 5-attempt window
    // rather than re-locking on the very next failure.
    const lockExpired = row.lockedUntil && row.lockedUntil <= now;
    const failedLoginAttempts = lockExpired ? 0 : row.failedLoginAttempts;
    const currentlyLocked = row.lockedUntil && row.lockedUntil > now;

    if (currentlyLocked) {
      return { status: "locked" };
    }

    if (!passwordCorrect) {
      const attempts = failedLoginAttempts + 1;
      const lockingNow = attempts >= LOCKOUT_THRESHOLD;
      // Still covered by the row lock acquired above — this write, and the
      // read that decided it, run inside the same transaction, so nothing
      // else can touch this row in between.
      await tx.user.update({
        where: { id: user.id },
        data: {
          failedLoginAttempts: lockingNow ? 0 : attempts,
          lockedUntil: lockingNow
            ? new Date(now.getTime() + LOCKOUT_DURATION_MS)
            : null,
        },
      });
      return lockingNow ? { status: "locked" } : { status: "invalid", remaining: LOCKOUT_THRESHOLD - attempts };
    }

    if (failedLoginAttempts !== 0 || row.lockedUntil) {
      await tx.user.update({ where: { id: user.id }, data: CLEARED_LOCKOUT });
    }
    return { status: "success" };
  });

  if (outcome.status === "locked") {
    throw AppError.locked(LOCKED_MESSAGE);
  }
  if (outcome.status === "invalid") {
    throw invalidCredentials(outcome.remaining);
  }

  // Suspension is revealed only after the password is proven correct — doing
  // it earlier would let a caller learn account status without knowing the
  // password.
  if (isSuspended(user)) {
    throw AppError.forbidden(SUSPENDED_ON_PASSWORD_PATH);
  }

  return { token: signToken({ sub: user.id }), user };
}

/**
 * FR-ACC-07 OTP login path, via Firebase Phone Authentication — same
 * server-side ID-token verification as registration (FR-ACC-08 AC3). Lets a
 * user log in without their password (FR-ACC-07 AC1), fully unaffected by
 * an active password lockout (product-overview.md: "the OTP path is
 * unaffected by that lock") — nothing in this function even reads
 * lockedUntil.
 *
 * Also clears any active password lockout on success — not required to
 * make this path work (requireAuth.js no longer enforces lockedUntil at
 * all, and this function never checked it), but proving phone ownership
 * via a fresh Firebase OTP is reasonable grounds to lift the password
 * lockout too, so the user isn't left waiting out the remaining 15
 * minutes on the password path after already proving who they are a
 * different way. Same as what a correct password does in
 * loginWithPassword above.
 *
 * @param {object} input
 * @param {string} input.idToken - Firebase ID token from client-side phone verification.
 * @returns {Promise<{ token: string, user: object }>}
 */
async function loginWithOtp({ idToken }) {
  if (!idToken || typeof idToken !== "string") {
    throw AppError.badRequest("idToken is required.", { idToken: "Required" });
  }

  let phoneNumber;
  try {
    ({ phoneNumber } = await verifyFirebaseIdToken(idToken));
  } catch (err) {
    console.error("verifyFirebaseIdToken failed during OTP login:", err);
    throw AppError.unauthorized(
      "Phone verification failed or has expired. Verify your phone again.",
    );
  }

  const user = await prisma.user.findFirst({
    where: { phone: phoneNumber, deletedAt: null },
  });
  if (!user) {
    throw AppError.unauthorized("No account found for this phone number.");
  }
  if (isSuspended(user)) {
    throw AppError.forbidden(SUSPENDED_ON_OTP_PATH);
  }

  await clearLockout(user.id);

  return { token: signToken({ sub: user.id }), user };
}

/**
 * Masks an address for display: "kavindu@example.com" -> "k*****@example.com". The reset
 * screen needs to tell the person which inbox the link will go to, but the endpoint that
 * does so is unauthenticated, so it must not hand the full address to anyone who types
 * a phone number.
 */
function maskEmail(email) {
  const [local, domain] = email.split("@");
  return `${local[0]}${"*".repeat(Math.max(local.length - 1, 3))}@${domain}`;
}

/**
 * FR-ACC-10: which reset channels this phone number can use. Unauthenticated, so the
 * answer for a number with no account and for a number with no verified email is the
 * same shape — nothing here confirms that an account exists.
 * @param {{ phone: string }} input
 * @returns {Promise<{ phone: string, email: string|null, emailVerified: boolean }>}
 */
async function resetPasswordChannels({ phone }) {
  if (!phone || typeof phone !== "string") {
    throw AppError.badRequest("Phone is required.", { phone: "Required" });
  }
  const normalizedPhone = normalizePhoneForLookup(phone);
  const user = await prisma.user.findFirst({
    where: { phone: normalizedPhone, deletedAt: null },
    select: { email: true, emailVerifiedAt: true },
  });

  // Only a VERIFIED email is a usable channel (FR-ACC-10 AC2), and only that one is shown.
  const hasVerifiedEmail = Boolean(user && user.email && user.emailVerifiedAt);
  return {
    phone: normalizedPhone,
    email: hasVerifiedEmail ? maskEmail(user.email) : null,
    emailVerified: hasVerifiedEmail,
  };
}

/**
 * FR-ACC-10: sends a reset code (PHONE) or link (EMAIL). Always answers { success: true }
 * — for an unknown number, an unusable channel, or a request over the rate limit — so the
 * response never reveals whether an account exists.
 * @param {{ phone: string, channel: "PHONE"|"EMAIL" }} input
 */
async function resetPasswordRequest({ phone, channel }) {
  if (!phone || typeof phone !== "string" || !channel) {
    throw AppError.badRequest("Phone and channel are required.");
  }
  if (channel !== "PHONE" && channel !== "EMAIL") {
    throw AppError.badRequest("Invalid channel");
  }
  const normalizedPhone = normalizePhoneForLookup(phone);

  // Each request sends an SMS or email; cap them per number. Over the cap the request is
  // dropped silently, exactly like an unknown number.
  const requestKey = `reset-request:${normalizedPhone}`;
  if (isBlocked(requestKey, RESET_REQUEST_LIMIT.max, RESET_REQUEST_LIMIT.windowMs)) {
    return { success: true };
  }
  record(requestKey, RESET_REQUEST_LIMIT.windowMs);

  const user = await prisma.user.findFirst({
    where: { phone: normalizedPhone, deletedAt: null },
  });
  if (!user) {
    return { success: true };
  }

  if (channel === "PHONE") {
    const code = await generateOtp({
      phone: user.phone,
      purpose: "PASSWORD_RESET",
      userId: user.id,
    });
    deliverInDevelopment("SMS", user.phone, code);
  } else {
    if (!user.email || !user.emailVerifiedAt) {
      return { success: true };
    }
    const token = await createResetToken(prisma, user, user.email);
    deliverInDevelopment(
      "Email",
      user.email,
      `${config.publicBaseUrl}/api/account/reset-password/page?token=${token}`,
    );
  }

  return { success: true };
}

/** Creates a single-use reset token (stored hashed) and returns the RAW token for the link/response. */
async function createResetToken(db, user, email) {
  const token = crypto.randomBytes(32).toString("hex");
  await db.emailVerificationToken.create({
    data: {
      userId: user.id,
      email,
      token: hashToken(token),
      purpose: "PASSWORD_RESET",
      expiresAt: new Date(Date.now() + RESET_TOKEN_MINUTES * 60 * 1000),
    },
  });
  return token;
}

/**
 * FR-ACC-10 / FR-ACC-08: checks the 6-digit code and, if right, hands back a short-lived
 * token for the "new password" step. A wrong code counts against a per-number limit,
 * because six digits are guessable without one.
 * @param {{ phone: string, code: string }} input
 */
async function resetPasswordVerify({ phone, code }) {
  if (!phone || !code || typeof phone !== "string" || typeof code !== "string") {
    throw AppError.badRequest("Phone and code are required.");
  }
  const normalizedPhone = normalizePhoneForLookup(phone);
  const failureKey = `reset-code:${normalizedPhone}`;
  if (isBlocked(failureKey, RESET_CODE_FAILURE_LIMIT.max, RESET_CODE_FAILURE_LIMIT.windowMs)) {
    throw AppError.tooManyRequests(
      "Too many wrong codes. Request a new code in a few minutes.",
    );
  }

  const user = await prisma.user.findFirst({
    where: { phone: normalizedPhone, deletedAt: null },
  });
  const isValid = user
    ? await verifyOtp({ phone: normalizedPhone, code, purpose: "PASSWORD_RESET" })
    : false;
  if (!isValid) {
    // Same count and same answer whether the number exists or not.
    record(failureKey, RESET_CODE_FAILURE_LIMIT.windowMs);
    throw AppError.unauthorized("Invalid or expired code.");
  }
  clear(failureKey);

  // The code was valid and is now consumed; issue the token for the next step.
  const token = await createResetToken(prisma, user, user.email || user.phone);
  return { success: true, token };
}

/**
 * FR-ACC-10 A3/A5: sets the new password. The token is claimed and the password changed in
 * ONE transaction, so a token cannot be spent twice by two simultaneous requests and a
 * failure cannot burn the token without changing the password. Stamping
 * passwordChangedAt is what makes requireAuth reject every session issued before now.
 * @param {{ token: string, newPassword: string }} input
 */
async function resetPasswordConfirm({ token, newPassword }) {
  if (typeof newPassword !== "string" || newPassword.length < 8 || newPassword.length > 64) {
    throw AppError.badRequest("Password must be between 8 and 64 characters.");
  }
  if (!token || typeof token !== "string") {
    throw AppError.badRequest("Must provide a reset token.");
  }

  const tokenHash = hashToken(token);
  const hash = await hashPassword(newPassword); // slow by design: done before the transaction opens

  await prisma.$transaction(async (tx) => {
    const row = await tx.emailVerificationToken.findFirst({
      where: { token: tokenHash, purpose: "PASSWORD_RESET", consumedAt: null, expiresAt: { gt: new Date() } },
      include: { user: true },
    });
    if (!row || !row.user || row.user.deletedAt) {
      throw AppError.unauthorized("Invalid or expired token.");
    }

    // Claim every outstanding reset token for this person at once: the one used, and any
    // older link still in an inbox. The count check makes a concurrent second use fail.
    const claimed = await tx.emailVerificationToken.updateMany({
      where: { userId: row.userId, purpose: "PASSWORD_RESET", consumedAt: null },
      data: { consumedAt: new Date() },
    });
    if (claimed.count === 0) {
      throw AppError.unauthorized("Invalid or expired token.");
    }

    await tx.user.update({
      where: { id: row.userId },
      data: {
        passwordHash: hash,
        passwordChangedAt: new Date(),
        failedLoginAttempts: 0,
        lockedUntil: null,
      },
    });
  });

  return { success: true };
}

/**
 * FR-ACC-10 E8: someone with no reachable phone and no verified email asks for an
 * Admin-reviewed recovery. The response is always { success: true } and reveals nothing
 * about whether the details matched an account.
 */
async function recoveryRequest({ nic, birthdate, legalName, deviceId }) {
  if (!nic || !birthdate || !legalName || !deviceId) {
    throw AppError.badRequest("All fields are required.");
  }
  assertDeviceId(deviceId);
  const birthdateValue = new Date(birthdate);
  if (Number.isNaN(birthdateValue.getTime())) {
    throw AppError.badRequest("Birthdate must be a valid date.", { birthdate: "Required, must be a valid date" });
  }
  if (typeof nic !== "string" || typeof legalName !== "string") {
    throw AppError.badRequest("All fields are required.");
  }

  // The NIC is matched using the same deterministic encryption that enforces uniqueness.
  const encryptedNic = encryptNic(nic);
  const user = await prisma.user.findFirst({
    where: {
      nicEncrypted: encryptedNic,
      legalName: { equals: legalName.trim(), mode: "insensitive" },
      birthdate: birthdateValue,
      deletedAt: null,
    },
  });

  await prisma.accountRecoveryRequest.create({
    data: {
      userId: user ? user.id : null,
      nicSubmittedEncrypted: encryptedNic,
      legalNameSubmitted: legalName.trim(),
      birthdateSubmitted: birthdateValue,
      deviceId,
    },
  });

  return { success: true };
}

/**
 * FR-ACC-10 E8: the outcome of this device's latest recovery request, shown only to the
 * device that asked. Returns the app-facing status words.
 * @returns {Promise<{ status: "pending"|"approved"|"rejected"|"used" }>}
 */
async function recoveryStatus({ deviceId }) {
  assertDeviceId(deviceId);
  const req = await prisma.accountRecoveryRequest.findFirst({
    where: { deviceId },
    orderBy: { createdAt: "desc" },
  });
  if (!req) {
    throw AppError.notFound("No request found.");
  }
  if (req.status === "APPROVED") {
    return { status: req.completedAt ? "used" : "approved" };
  }
  return { status: req.status === "REJECTED" ? "rejected" : "pending" };
}

/** FR-ACC-10 E8: on the requesting device only, an approved recovery lets the person set a new password. */
async function recoveryConfirm({ deviceId, newPassword }) {
  assertDeviceId(deviceId);
  if (typeof newPassword !== "string" || newPassword.length < 8 || newPassword.length > 64) {
    throw AppError.badRequest("Password must be between 8 and 64 characters.");
  }

  const hash = await hashPassword(newPassword);
  await prisma.$transaction(async (tx) => {
    const req = await tx.accountRecoveryRequest.findFirst({
      where: { deviceId, status: "APPROVED", completedAt: null },
      orderBy: { createdAt: "desc" },
      include: { user: true },
    });
    if (!req || !req.user || req.user.deletedAt) {
      throw AppError.unauthorized("No approved, unused recovery request found for this device.");
    }
    // Claim the grant first so two simultaneous confirms cannot both use it.
    const claimed = await tx.accountRecoveryRequest.updateMany({
      where: { id: req.id, completedAt: null },
      data: { completedAt: new Date() },
    });
    if (claimed.count === 0) {
      throw AppError.unauthorized("No approved, unused recovery request found for this device.");
    }
    await tx.user.update({
      where: { id: req.user.id },
      data: {
        passwordHash: hash,
        passwordChangedAt: new Date(),
        failedLoginAttempts: 0,
        lockedUntil: null,
      },
    });
  });

  return { success: true };
}

/**
 * FR-ACC-12: change the phone number. Gated behind the current password and a fresh
 * Firebase verification of the NEW number. The old number keeps satisfying the uniqueness
 * constraint until this single update swaps it, so the swap is atomic (AC2, AC3).
 * @param {{ userId: string, password: string, idToken: string }} input
 */
async function changePhone({ userId, password, idToken }) {
  if (!password || typeof password !== "string") {
    throw AppError.badRequest("Password is required.", { password: "Required" });
  }
  if (!idToken || typeof idToken !== "string") {
    throw AppError.badRequest("Phone verification token is required.");
  }

  // The password is being re-checked on an already signed-in session, so a stolen session
  // could otherwise guess it here without ever hitting the login lockout.
  const failureKey = `phone-change:${userId}`;
  if (isBlocked(failureKey, PHONE_CHANGE_FAILURE_LIMIT.max, PHONE_CHANGE_FAILURE_LIMIT.windowMs)) {
    throw AppError.tooManyRequests("Too many attempts. Try again in a few minutes.");
  }

  const user = await prisma.user.findUnique({ where: { id: userId } });
  if (!user || user.deletedAt) throw AppError.sessionEnded();

  const validPassword = await verifyPassword(password, user.passwordHash);
  if (!validPassword) {
    record(failureKey, PHONE_CHANGE_FAILURE_LIMIT.windowMs);
    // 400 with a field error, NOT 401: the session is fine, only this entry is wrong, and a
    // 401 would be read by the app as "your session has ended".
    throw AppError.badRequest("That password doesn't match your account. Please try again.", {
      password: "Incorrect password",
    });
  }
  clear(failureKey);

  let newPhone;
  try {
    ({ phoneNumber: newPhone } = await verifyFirebaseIdToken(idToken));
  } catch (err) {
    console.error("verifyFirebaseIdToken failed during phone change:", err);
    throw AppError.badRequest("Phone verification failed or has expired. Verify your phone again.");
  }

  if (newPhone === user.phone) {
    throw AppError.badRequest("This is already your registered phone number.");
  }

  const existingPhone = await prisma.user.findFirst({
    where: { phone: newPhone, phoneVerifiedAt: { not: null }, deletedAt: null },
    select: { id: true },
  });
  if (existingPhone) {
    throw AppError.conflict("That phone number is already registered.", { phone: "Already registered" });
  }

  try {
    await prisma.user.update({
      where: { id: userId },
      // The new number was just verified, so its verification time is now.
      data: { phone: newPhone, phoneVerifiedAt: new Date() },
    });
  } catch (err) {
    // The partial unique index caught a registration that raced this change.
    if (err.code === "P2002") {
      throw AppError.conflict("That phone number is already registered.", { phone: "Already registered" });
    }
    throw err;
  }

  return { success: true, phone: newPhone };
}

export default {
  register,
  verifyEmail,
  loginWithPassword,
  loginWithOtp,
  checkAvailability,
  resetPasswordChannels,
  resetPasswordRequest,
  resetPasswordVerify,
  resetPasswordConfirm,
  recoveryRequest,
  recoveryStatus,
  recoveryConfirm,
  changePhone,
};
